development:
  dialect: postgres
  datasource: host=db port=5432 dbname=app user=admin password=admin sslmode=disable
  dir: db/migrations
  table: migrations

pdoduction:
  dialect: postgres
  datasource: $MIGRATION_DATASOURCE
  dir: db/migrations
  table: migrations
