version: '3'
services:
  app:
    build: ./docker/go
    container_name: app
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    environment:
      - TZ=Asia/Tokyo
    ports:
      - 8080:8080
    links:
      - db
  db:
    build: ./docker/postgresql
    container_name: db
    volumes:
      - ./docker/postgresql/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=app
      - TZ=Asia/Tokyo
    ports:
        - 5433:5432

  test-db:
    build: ./docker/postgresql
    container_name: test-db
    volumes:
      - ./docker/postgresql/data:/var/lib/postgresql/test_data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=test_app
      - TZ=Asia/Tokyo
    ports:
        - 5434:5432
